AppDispatcher = require('../dispatcher/app_dispatcher')

TodoActions = {

  create: (text) ->
    AppDispatcher.dispatch
      actionType: TodoConstants.TODO_CREATE
      text: text
    return

  updateText: (id, text) ->
    AppDispatcher.dispatch
      actionType: TodoConstants.TODO_UPDATE_TEXT
      id: id
      text: text
    return

  toggleComplete: (todo) ->
    id = todo.id
    if todo.complete
      AppDispatcher.dispatch
        actionType: TodoConstants.TODO_UNDO_COMPLETE
        id: id
    else
      AppDispatcher.dispatch
        actionType: TodoConstants.TODO_COMPLETE
        id: id
    return

  toggleCompleteAll: ->
    AppDispatcher.dispatch actionType: TodoConstants.TODO_TOGGLE_COMPLETE_ALL
    return

  destroy: (id) ->
    AppDispatcher.dispatch
      actionType: TodoConstants.TODO_DESTROY
      id: id
    return

  destroyCompleted: ->
    AppDispatcher.dispatch actionType: TodoConstants.TODO_DESTROY_COMPLETED
    return
}

module.exports = TodoActions

# ---
# generated by js2coffee 2.0.0
